// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
/*import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQbVXtIfJcY1guKUR3U2avbIvUVBNhNs8',
    appId: '1:145857208204:web:63ca10178d14a2fb7dc0a9',
    messagingSenderId: '145857208204',
    projectId: 'tyxuan-6c448',
    authDomain: 'tyxuan-6c448.firebaseapp.com',
    storageBucket: 'tyxuan-6c448.appspot.com',
    measurementId: 'G-PG49PETZDW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqu1VbCE0cUR6CxNGSGP0HRTYN-95HbzM',
    appId: '1:145857208204:android:856e9daf65d341e07dc0a9',
    messagingSenderId: '145857208204',
    projectId: 'tyxuan-6c448',
    storageBucket: 'tyxuan-6c448.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJjJLUD0T1k9UGxBmpYRmeonRrJX_6N98',
    appId: '1:145857208204:ios:0f7c8fec12d9a8887dc0a9',
    messagingSenderId: '145857208204',
    projectId: 'tyxuan-6c448',
    storageBucket: 'tyxuan-6c448.appspot.com',
    iosBundleId: 'com.ahkah.production.production',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJjJLUD0T1k9UGxBmpYRmeonRrJX_6N98',
    appId: '1:145857208204:ios:0b2fc0a952da4dd57dc0a9',
    messagingSenderId: '145857208204',
    projectId: 'tyxuan-6c448',
    storageBucket: 'tyxuan-6c448.appspot.com',
    iosBundleId: 'com.ahkah.production.production.RunnerTests',
  );
}
*/